# Generated by Django 3.0.7 on 2020-06-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='discription',
            new_name='description',
        ),
    ]
