# Generated by Django 3.0.6 on 2020-06-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msat', '0003_auto_20200518_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='msat',
            name='email',
            field=models.EmailField(default='xx@xx.com', max_length=200),
        ),
    ]
