# Generated by Django 3.0.7 on 2020-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msat', '0005_auto_20200724_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msat',
            name='response',
            field=models.CharField(max_length=1000),
        ),
    ]
