# Generated by Django 3.0.7 on 2020-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msat', '0006_auto_20200724_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msat',
            name='response',
            field=models.CharField(max_length=500),
        ),
    ]
