# Generated by Django 3.1.1 on 2021-03-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
